//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipSistemiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class birimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public birimler()
        {
            this.personeller = new HashSet<personeller>();
        }
    
        public int birimId { get; set; }
        public string birimAd { get; set; }
        public Nullable<bool> aktiflik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personeller> personeller { get; set; }
    }
}
