//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipSistemiMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isTakipDBEntities : DbContext
    {
        public isTakipDBEntities()
            : base("name=isTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<birimler> birimler { get; set; }
        public virtual DbSet<durumlar> durumlar { get; set; }
        public virtual DbSet<isler> isler { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<yetkiTurler> yetkiTurler { get; set; }
        public virtual DbSet<Loglar> Loglar { get; set; }
    }
}
