//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipSistemiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personeller()
        {
            this.isler = new HashSet<isler>();
            this.Loglar = new HashSet<Loglar>();
        }
    
        public int personelId { get; set; }
        public string personelAdSoyad { get; set; }
        public string personelKullanıcıAd { get; set; }
        public string personelParola { get; set; }
        public Nullable<int> personelBirimId { get; set; }
        public Nullable<int> personelYetkiTurId { get; set; }
        public Nullable<bool> yeniPersonel { get; set; }
        public Nullable<bool> aktiflik { get; set; }
    
        public virtual birimler birimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isler> isler { get; set; }
        public virtual yetkiTurler yetkiTurler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loglar> Loglar { get; set; }
    }
}
